baseURL = "http://www.cinetenisverde.com.br/"
languageCode = "en-us"
title = "Cine Tênis Verde"
theme = "hugo-xmin"
googleAnalytics = "UA-50557403-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/:filename/"
    note = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 6

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Facebook](https://www.facebook.com/cinetenisverde/) | [Twitter](https://twitter.com/cinetenisverde) | [Github](https://github.com/Caloni/cinetenisverde)"
    googleSearch = "005399618489749432245:uxhode2mus4"
