baseURL = "http://www.cinetenisverde.com.br/"
languageCode = "en-us"
title = "Cine Tênis Verde"
theme = "capsule"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/:filename/"
    note = "/:filename/"

[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 1

[params]
    description = "A website built through Hugo and blogdown."
    googleSearch = "005399618489749432245:uxhode2mus4"
    googleAnalytics = "UA-50557403-1"
    yandexVerification = "48a8210fc043c5e8"
