baseURL = "http://www.cinetenisverde.com.br/"
languageCode = "en-us"
title = "Cine Tênis Verde"
theme = "hugo-xmin"
googleAnalytics = "UA-50557403-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "?"

[permalinks]
    post = "/:filename/"
    note = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 3

[params]
    description = "A website built through Hugo and blogdown."
    footer = "[Facebook](https://www.facebook.com/cinetenisverde/) | [Twitter](https://twitter.com/cinetenisverde) | [Github](https://github.com/Caloni/cinetenisverde) | [CinemAqui](https://github.com/Caloni/cinetenisverde/tree/master/content/cinemaqui) | [About](/about)"
    googleSearch = "005399618489749432245:uxhode2mus4"
